# Cargo.toml

[package]
name = "streaming-stampede"
version = "0.0.2"
authors = ["Giorgio Pomettini"]

[profile.dev]
opt-level = 1

[dependencies]
ggez = "0.4"
ggez-goodies = { git = "https://github.com/ggez/ggez-goodies", rev = "aacd12867d886b0331478ab616dcb35e337643a8" }